### ISSUE TITLE
Possible memory leak when viewing files

### ISSUE THREAD

**Issue by NeRdTheNed** [benwiggy/APPlayMIDI#11]
Viewing midi files increases the memory used by APPlayMIDI or the quick look plugin, but closing files does not seem to release all memory associated with the closed file. This is easiest to replicate for me by rapidly previewing files using the quick look plugin (playback is not required to replicate this), resulting in the used memory increasing for each preview.

After previewing some files (nothing currently playing, no open quick look windows):

<img width="231" alt="Screen Shot 2023-09-08 at 9 39 00 am" src="https://github.com/benwiggy/APPlayMIDI/assets/41816363/e524b290-70ae-40e1-b521-15d2d247c66b">

After previewing some more files (nothing currently playing, no open quick look windows):

<img width="222" alt="Screen Shot 2023-09-08 at 9 39 52 am" src="https://github.com/benwiggy/APPlayMIDI/assets/41816363/fa286aea-b213-402e-8e04-9eac94f13b90">

Tested with version 1.10 of APPlayMIDI on macOS 12.6.8, running on a M1 processor.

**Comment by benwiggy** [comment]
Yes. Thanks for pointing that out. I'll have a look and see if I can find what's doing that.

**Comment by benwiggy** [comment]
I've made some adjustments, and from what I can tell, they may have improved things. Version 1.12 is now available. 
Let me know. I think macOS doesn't always release memory from processes, though.

**Comment by NeRdTheNed** [comment]
@benwiggy It looks like the memory issue is solved, thanks!
