### ISSUE TITLE
Couple of feature requests - MIDI output device chooser & ability to mute/solo channels

### ISSUE THREAD

**Issue by richb93** [benwiggy/APPlayMIDI#13]
Hello! Just found this app and it looks good, but I have a couple of requests:

- The ability to choose the MIDI output device - so if I plug in a USB MIDI interface, I can output the MIDI to an external synthesiser.
- The ability to mute or solo specific channels - this would be nice so if I have a song with a vocal guide track, I can mute it.

Thanks for a great lightweight app!

Cheers,
Rich

**Comment by benwiggy** [comment]
The app is intended to be a simple 'previewer' of MIDI files, similar to the functionality that was in QuickTime Player in 2009. 
It literally just passes the MIDI file as a whole to the OS's own MIDI player.

I'm afraid I don't plan to introduce features such as these.
