### ISSUE TITLE
Clarify license?

### ISSUE THREAD

**Issue by dspreadbury** [benwiggy/APPlayMIDI#3]
Thanks for writing this app, Ben. Have you considered adding some explicit information about the license under which the software is released? I would suggest using the MIT License unless any of the libraries/code snippets you used in the creation of the application would preclude that.

**Comment by benwiggy** [comment]
Yes, very good point. I must defer to m'learned friend in such matters. Is it sufficient just to write "This is released under the MIT Licence" in the read me?

**Comment by dspreadbury** [comment]
It should be sufficient to put the text of the MIT license in a text file called LICENSE in the root of your repository.

GitHub docs here: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Text of MIT license (with spaces for project name and copyright info etc.) here: https://opensource.org/licenses/MIT

**Comment by benwiggy** [comment]
Done!
