### ISSUE TITLE
Fails Gatekeeper Verification

### ISSUE THREAD

**Issue by alvarnell** [benwiggy/APPlayMIDI#4]
v1.02 failed Gatekeeper verification in Mojave. 
% spctl -a -t exec -vv /Applications/APPlayMIDI.app 
/Applications/APPlayMIDI.app: rejected
origin=Apple Development: benbwster@gmail.com (QX77QEJWTJ)

Checking with RB App Checker Lite shows following:

Evaluating the application “APPlayMIDI”.

The application was signed by “Apple Root CA”, “Apple Development: benbwster@gmail.com (QX77QEJWTJ)”.
	The (unverified) signing-time is: Feb 15, 2020 at 08:02:17.
	The object code format is “app bundle with Mach-O thin (x86_64)”.
	The signature contains the Team ID “GDSEUFVD4C”.
	Both bundle and signing identifiers are “bensoft.APPlayMIDI”.
	The signature specifies implicit requirements. ￼
	The signature specifies resource rules (v1). ￼
	The signature specifies resource rules (v2). ￼
	Gatekeeper assessment: FAIL (missing/invalid authority). ￼ ￼
raw assessment: {
    "assessment:authority" =     {
        "assessment:authority:flags" = 0;
    };
    "assessment:remote" = 1;
    "assessment:verdict" = 0;
}
	Requirements and resources validate correctly.

The code signature has the UUID “993CF9AD-3522-648C-C732-AC259AA7AADE”.
	Executable code for x86_64 has the UUID “B5486907-BAF1-3B27-8394-039755E9C221”.

A signing-time snapshot of the application’s Info.plist was found. ￼
	Version 1.02 (58) Copyright © 2019 Ben. All rights reserved.

The signature contains 3 certificates. ￼
	Certificate “Apple Root CA”: ￼
		Your keychain contains this trusted root certificate.
		Will expire on Feb 9, 2035.
	Certificate “Apple Worldwide Developer Relations Certification Authority”: ￼
		Will expire on Feb 7, 2023.
	Certificate “Apple Development: benbwster@gmail.com (QX77QEJWTJ)”: ￼
		Will expire on Feb 14, 2021.
		SHA1 fingerprint: “DD5EB0AD64E298F1A05CF2A0C3162D7DC7E70BBA”.
		Team ID or Organizational Unit: “GDSEUFVD4C”.
			This matches the Team ID contained in the signature.

The application is not sandboxed.

The code signature contains entitlements. ￼
	Other entitlements:
		com.apple.security.get-task-allow: YES.

The application is quarantined. ￼

8 auxiliary executables have been found. ￼
	8 executables are signed by  “Apple Root CA”, “Apple Development: benbwster@gmail.com (QX77QEJWTJ)”. ￼

**Comment by benwiggy** [comment]
Thank for this. Though it seems to be giving mixed messages: I don't understand why it fails if it has valid certs. 

Does it open on first launch, without having to do the right-click Command-Open trick?

**Comment by alvarnell** [comment]
No, it does not open on first launch:
<img width="532" alt="Screen Shot 2020-03-18 at 02 18 00" src="https://user-images.githubusercontent.com/4943704/76944780-d4b61880-68be-11ea-95ce-a4ef8bfac201.png">

**Comment by benwiggy** [comment]
It seems it's not possible to get through GateKeeper without paying Apple, so I'll remove the certificate as it will expire and is pointless, and Close this.
