### ISSUE TITLE
Support PitchBend calls

### ISSUE THREAD

**Issue by mscuthbert** [benwiggy/APPlayMIDI#7]
Fantastic app -- Thank you for making it!

It would be great if PitchBend messages were supported in MIDI files -- a lot of users use my music21 package to create microtonal MIDI files and we write them out to MIDI files, but at the moment, APPlayMIDI does not seem to support them.  I'll try over the Spring to learn enough Swift (it's close enough to Python, right?) to contribute a patch, but wanted to note it in case I can't get it.  Again -- thanks!  Nothing but happiness to know this program exists.

**Comment by benwiggy** [comment]
Hmm. I knocked up a MIDI file with some pitch bends in Logic, and the bends are clearly played in the app. Here's the file: I don't know whether there's anything particularly special about the use of pitch bend in it. (There's only about 20 seconds or so, but the file is 4 mins - blame Logic.)
[Bend.mid.zip](https://github.com/benwiggy/APPlayMIDI/files/5775202/Bend.mid.zip)

To be fair, all the app does is pass the MIDI to Apple's built-in MIDI playback generator, so I don't know how you'd contemplate acting on particular MIDI datas. 

Also: love your work. I'm planning to get stuck into music21 this year!
