### ISSUE TITLE
Asks for 12.0 or later

### ISSUE THREAD

**Issue by Bottacco** [benwiggy/APPlayMIDI#8]
Hi, I have just downloaded this new version and installed it in 10.15.7 Catalina but the icon appears with a forbidden sign and when you double click it to open it says that you need 12.0 or later. I imagine it is some flag in the compilation script… but you will know for sure.

Thank you very much for this useful utility and cheers from Spain,

VB

**Comment by Bottacco** [comment]
I was using 1.02 and it works fine, but I have just downloaded 1.04 and 1.05 and both say that I need Big Sur 11 to run them.

**Comment by benwiggy** [comment]
Sorry for the confusion. Let me be more accurate:
v1.10 does need macOS 12, Monterey, for the Quick Look extension to work.
v.1.04 and 05 are Universal Binaries for Intel and Apple Silicon, and so require Big Sur to work. 
v1.02 should work on earlier OSes.

**Comment by ahihi** [comment]
> v1.10 does need macOS 12, Monterey, for the Quick Look extension to work.
> v.1.04 and 05 are Universal Binaries for Intel and Apple Silicon, and so require Big Sur to work.
> v1.02 should work on earlier OSes.

it would be helpful to have this information in the README, which currently only says "Runs on Sierra (10.12) and above".

**Comment by benwiggy** [comment]
Thanks. That's now been added.
