### ISSUE TITLE
Quick Look Playback Blocked

### ISSUE THREAD

**Issue by velanche** [benwiggy/APPlayMIDI#9]
Greets:
Seems that the ability to use Quick Look to preview MIDI files has been blocked.

When I attempt to preview MIDI files, a dialog box pops up with the following: 

"'APPlayMIDI' can’t be opened because Apple cannot check it for malicious software.

"This software needs to be updated. Contact the developer for more information."

I have the latest version of the player on MacOS Ventura 13.2.1. The window pops up immediately after I choose a MIDI file.

**Comment by benwiggy** [comment]
That's because the app isn't signed. (Because I don't pay Apple $99 per year.) Right-click on the app, and select Open. You should then be given the option to proceed.
https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by velanche** [comment]
Thanks for the quick reply; glad that the solution was that simple.

Good to also know of this:

“The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app.”

I appreciate the help.
V.

From: benwiggy ***@***.***>
Date: Thursday, February 16, 2023 at 1:45 PM
To: benwiggy/APPlayMIDI ***@***.***>
Cc: velanche ***@***.***>, Author ***@***.***>
Subject: Re: [benwiggy/APPlayMIDI] Quick Look Playback Blocked (Issue #9)

That's because the app isn't signed. (Because I don't pay Apple $99 per year.) Right-click on the app, and select Open. You should then be given the option to proceed.
https://support.apple.com/en-gb/guide/mac-help/mh40616/mac
